#!/usr/bin/env perl
#
# Copyright 2016, Barry(Kui Xu) < kuixu.tj@gmail.com >
# 
# This commline email tool is for linux users to notify the progress of your task.
# For example, you submit a long-time-running job with ==xmail==, then you will receive
# a notify message from xmail with a warning that your task is finished.
#

use Emailesque;
use Getopt::Std;

use vars qw ($opt_h $opt_u $opt_s $opt_m);
&getopts('hu:s:m:');

my $user="zhanglab163@163.com";
my $pass="b1002b1002";

my $usage = <<_EOH_;
 ----------xmail----------------

Usage:
        xmail -u useremail -s subject -m message [-option value]

Option 
        -u      [str]*  the email you want to send notification to. eg. xxx\@gmail.com
        -s      [str]*  the subject of the email.
        -m      [str]   more detaills can be placed.  
    
        -h              print this usage        

Examples:
        xmail -u xxx\@gmail.com -s "xxx task completed!"


xmail Version 0.0.1 
By Kui From ZhangLab 
_EOH_
;

sub init
{
    die $usage if ( $opt_h || not defined $opt_u ||not defined $opt_s);
    $opt_m = $opt_s if ( not defined $opt_m );
    1;
}
&init();


my $to=$opt_u;
my $sub=$opt_s;
my $msg=$opt_m;
print "=======> xmail   By Kui. <=======\nemail:$to\nsub:$sub\nmsg:$msg\n=================================\n";
#my $email = Emailesque->new(
#    to      => 'xxx@gmail.com',
#    from    => 'xxx@163.com',
#    subject => 'test perl',
#    message => 'Working on Hash::Merge::Simple',
  #  files   => [ '/path/to/file/1', '/path/to/file/2' ],
#);
my $datetime = localtime;
my $email = Emailesque->new(
    to      => $to,
    from    => 'zhanglab163@163.com',
    subject => $sub,
    message => $msg."\n\n$datetime\n-------------------\n\n xmail   v1.0    \nBy Kui From ZhangLab.",
  #  files   => [ '/path/to/file/1', '/path/to/file/2' ],
);
my $result = $email->send({
#    ...,
    ssl     => 1,
    driver  => 'smtp',
    host    => 'smtp.163.com',
    port    => 465,
    user    => 'zhanglab163@163.com',
    pass    => 'b1002b1002'
});

if ($result->isa('Email::Sender::Failure')) {
    die $result->message;
}
